name: Daily Thought Update

on:
  schedule:
    # Runs at 8:00 AM IST every day.
    # IST is UTC+5:30. So, 8:00 AM IST is 2:30 AM UTC.
    - cron: '30 2 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI

jobs:
  update-thought:
    runs-on: ubuntu-latest
    permissions: # This grants the GITHUB_TOKEN permission to push changes
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          # Add any pip installs your script needs, e.g.,
          # pip install requests

      - name: Configure Git for Contribution
        run: |
          git config --global user.name "Adhishree21"
          git config --global user.email "adhishreeshiledar21@gmail.com"

      - name: Run Python script to update README
        run: python update_thought.py

      - name: Commit and push if changes exist
        run: |
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "✨ Daily Thought Update: $(date +'%Y-%m-%d')"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}